version: '3.8'

services:
  mariadb:
    image: mariadb:ael-fagr
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:ael-fagr
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always

    networks:
      - mynetwork
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: youruser
      WORDPRESS_DB_PASSWORD: yourpassword
      WORDPRESS_DB_NAME: yourdb
    volumes:
      - db_data:/var/www/html

  nginx:
    image: nginx:ael-fagr
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: {}
