version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - mynetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    networks:
      - mynetwork

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
