version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    networks:
      - mynetwork
    volumes:
      - db_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: {}
