version: '3.8'

services:

  wordpress:
    image: wordpress:ael-fagr
    build: ./requirements/wordpress
    restart: always
    networks:
      - mynetwork
    env_file:
      - .env
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
  
  mariadb:
    image: mariadb:ael-fagr
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - /home/$USER/data/mariadb:/var/lib/mysql

  nginx:
    image: nginx:ael-fagr
    build: ./requirements/nginx
    restart: always
    env_file :
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - /home/$USER/data/wordpress:/usr/share/nginx/html

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: /home/$USER/data/wordpress
