version: '3.8'

services:
  wordpress:
    image: wordpress:ael-fagr
    build: ./requirements/wordpress
    restart: always
    networks:
      - mynetwork
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: youruser
      WORDPRESS_DB_PASSWORD: yourpassword
      WORDPRESS_DB_NAME: yourdb
    depends_on:
      - mariadb
    volumes:
      - db_data:/var/www/html
  
  mariadb:
    image: mariadb:ael-fagr
    build: ./requirements/mariadb
    restart: always
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:ael-fagr
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
